### ISSUE TITLE
test.js fails to start

### ISSUE THREAD

**Issue by nickretallack** [Vaporbook/epub2web#3]
When I run node test/test.js, or any js file in the test directory, this happens:

```
/Users/nick/node_modules/epub2web/lib/epub2web.js:12
var parser = cacher.getParser();
                    ^
TypeError: Object #<Object> has no method 'getParser'
    at Object.<anonymous> (/Users/nick/node_modules/epub2web/lib/epub2web.js:12:21)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/nick/node_modules/epub2web/index.js:1:80)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

**Comment by Vaporbook** [comment]
I believe the git repo was out of sync with npm. At my last test, this now works.
